version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: shisha-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Secret123!
      - POSTGRES_DB=ShishaDb
    volumes:
      - shisha_pg_data:/var/lib/postgresql/data
    networks:
      - shisha-network
    restart: always

  # shishabuilder.web:
  #   build:
  #     context: .
  #     dockerfile: ShishaBuilder.Web/Dockerfile
  #   container_name: shisha-web
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - ASPNETCORE_URLS=http://+:80
  #     - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ShishaDb;Username=postgres;Password=Secret123!
  #   depends_on:
  #     - postgres
  #   networks:
  #     - shisha-network
  #   restart: always

volumes:
  shisha_pg_data:

networks:
  shisha-network:
    driver: bridge